### ISSUE TITLE
Evaluate if we need the package gr-flowgraph at all

### ISSUE THREAD

**Issue by alexxcons** [fair-acc/gr-digitizers#42]
In GitLab by @alexxcons on Mar 21, 2019, 09:55

Theoretically gnuradio already has methods which do exactly the same than we do in gr-flowgraph (parse xml file, create all blocks, links all blocks, evaulate variables... )
- check if gnuradio can handle our self-build blocks (check on local computer, using gnuradio-companion)
- If possible, dump the package gr-flowgraph, and directly use gnuradio code instead

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 21, 2019, 09:58

marked this issue as related to #12

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 21, 2020, 19:35

Email zum Thema von R.Steinhagen:

> GNURadio hat ab 3.8 eine 'C++ generation' feature, dass i.W. über die yml templates gesteuert wird. z.B.
> 
```
[..]
cpp_templates:
    includes: [ '#include <gnuradio/audio/source.h>' ]
    declarations: 'audio::source::sptr ${id};'
    make: 'this->${id} = audio::source::make(${samp_rate}, ${device_name}, ${ok_to_block});'
    link: ['gnuradio-audio']
    translations:
        "'": '"'
        'True': 'true'
        'False': 'false'
[..]
```
> Siehe auch: https://github.com/gnuradio/gnuradio/issues/2297
> Viele der Module sind schon dafür vorbereitet bzw. im master gemerged.... die restlichen sollten bald auch da sein. Wichtig ist, dass wir unsere diesbzgl. auch vorbereiten.
> 
> Daraus kann man (ähnlich wie das GRC mit python macht) die stubs generieren, die man braucht um die grc Files einzulesen und mit den statischen Werten im grc File zu initialisieren und Sinks/Sources im flow-graph zu connecten.
> 
> Die Idee wäre daraus -- ähnlich wie bei dem bestehendem gr-flowgraph -- eine look-up Funktion für jeden Block zu generieren, aber halt automatisch und nicht händisch wie das bisher geschieht. Ungeachtet davon muss FESA aber für die benötigten und konfigurierbaren Module (z.B. input gain, Soll-ist-Vergleich, Fitter, ...) beigebracht bekommen zur Laufzeit  Modulparameter zu ändern. Da wird's wohl immer noch handgestrickten Code (wegen FESA) geben müssen. Aber die Initialisierung sollte mit obigen automatisch geschehen können. Diese Modul würde dann immer neu gebaut, wenn eines unserer anderen Module neugebaut werden würde... deshalb CI/CD und alle GSI Module im gleichen Repo, damit das etwas einfacher ist.
> 
> Bzgl. Time-Line... wir werden damit vermutlich noch nicht vor Ende der Strahlzeit richtig anfangen können, da davor noch ein paar UI und CMW-Themen erst einmal fertig gemacht werden müssen.
